### ISSUE TITLE
Curser visualisation of whether or not CodeField is selected

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#3]
**Is your feature request related to a problem? Please describe.**
The problem this is meant to fix is confusion over which box is selected. Since I  use `outline: none` there is no visual way of telling if CodeField is selected as of now.

**Describe the solution you'd like**
Have the cursor be a outline when CodeField is not selected and filled when it is. Other visualisations could work as well.

**Comment by cobwebsonsale** [comment]
Hey, I've submitted a PR for a fix for this issue. Let me know if it's alright or if there are any changes required. I also added an indicator for the cursor using border-bottom. Here's a demo:
![demo](https://user-images.githubusercontent.com/1848127/96299735-1a33f300-1012-11eb-831c-e9a393693c1d.gif)
