### ISSUE TITLE
Automatically scroll down to newest message

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#42]
**Is your feature request related to a problem? Please describe.**
You have to manually scroll down to the bottom to read the newest messages.

**Describe the solution you'd like**
When a new message is added, the chat scrolls all the way down to the bottom of chat box automatically.

**Comment by cobwebsonsale** [comment]
Added a simple change for this. Let me know if it works for you.
![scroll](https://user-images.githubusercontent.com/1848127/96331470-1a1c0d80-107b-11eb-99cd-8ab4b9db3ac8.gif)
