### ISSUE TITLE
Missing check on key down

### ISSUE THREAD

**Issue by KovaCro** [olavfosse/liracer#43]
**Describe the bug**
"Alt Gr" gets registered as a key used to write a letter. In my case; Croatian keyboard creates "{" with a combination of "Alt Gr" and "B" which means there is no way for me to race because I can never put "{" without having a type error because there is no statement that checks if the key is "Alt Gr".

**To Reproduce**
Try to write a symbol that requires a combination of Alt Gr + something or just try pressing Alt Gr while in the race.

**Expected behaviour**
OnKeyDown should return without doing anything if the key is Alt Gr.

**Fix suggestions**
Add a check (if statement) in the event handler.

**Comment by olav35** [comment]
Hello, thanks for reporting. What is the `event.key` of Alt Gr? 

Use https://keycode.info/

**Comment by olavfosse** [comment]
I deployed a new frontend where this should be fixed. Sorry for the inconvenience, it should work correctly now.
