### ISSUE TITLE
[LINEFEED] key is not checking properly in Liracer

### ISSUE THREAD

**Issue by hungthezorba** [olavfosse/liracer#50]
**Describe the bug**
Enter key (or [LINEFEED] in Ascii) is not recognized correctly in the game. In some snippet, \n is expected to have the Ascii code of 13 which is [CARRIAGE RETURN], however, the Enter Key has the Ascii code of 10 which is [LINEFEED]. Resulting the Liracer always determines that player hit the incorrect key.

**Expected behavior**
It should recognize [LINEFEED] key as the [CARRIAGE RETURN] and vice versa.

**Screenshots**
This is where the snippet code has a breakline character.

![image](https://user-images.githubusercontent.com/51154273/96397797-82dac580-11f4-11eb-800b-c00ea88cdea4.png)

I put the console.log() in the code for better visualization.

![image](https://user-images.githubusercontent.com/51154273/96398133-49ef2080-11f5-11eb-8158-a045353ee310.png)

**Operating Systems**
Windows 10

**Web Browsers**
Firefox, Microsoft Edge

**Comment by hungthezorba** [comment]
I did a test on MacOS with Microsoft Edge, Firefox and it works properly, so I guess the problem is due to the OS.

**Comment by olavfosse** [comment]
> I did a test on MacOS with Microsoft Edge, Firefox and it works properly, so I guess the problem is due to the OS.

Do you have this problem on all snippets on Windows? If it only happens on some, can you give an example of a snippet you have it on.

**Comment by hungthezorba** [comment]
> > I did a test on MacOS with Microsoft Edge, Firefox and it works properly, so I guess the problem is due to the OS.
> 
> Do you have this problem on all snippets on Windows? If it only happens on some, can you give an example of a snippet you have it on.

Apparently, this problem has in all snippets has '\n' in the code such as LeapYear.java.
![bugEnter](https://user-images.githubusercontent.com/51154273/96533200-a9ae0000-12b7-11eb-815e-7483f4b1b133.gif)

As you can see here, when the cursor reach the end of the line, it should show '↵', however, it did not.

**Comment by olavfosse** [comment]
I'm guessing windows read newline as carriage return for some reason. I don't have a windows box at hand at the time, but I'll try mapping over the snippets such that carriage return is replaced with proper newlines. I'll make a PR then you can verify if it works for you.

**Comment by olavfosse** [comment]
>I'm guessing windows read newline as carriage return

iirc I read something about that in a C book.

Anyways, please checkout https://github.com/olav35/liracer/pull/56 and report if it fixes your issue or not.
