### ISSUE TITLE
Add /nick command 

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#55]
**Is your feature request related to a problem? Please describe.**
Identifying people by their playerID is cumbersome.

**Describe the solution you'd like**
There should be a /nick command, like in IRC, that sets your nickname. It should persist between games.

**Implementation Suggestions**
KISS
- No authorization/authentication (no passwords / passkeys)
- Multiple users can have the same nickname in the same game. We have the IDs to differentiate people with the same nick.
- Possibly reserve some nicks for liracer developers.

The implementation should be as simple as possible. No authorization / authentication is needed

**Comment by hungthezorba** [comment]
If the player set his nick, it will replace the '<anon>' or replace the playerID in the hovering part ?

**Comment by olavfosse** [comment]
>replace the "

I'm guessing this is a markup mistake, but I think I understand what you are asking either way. Btw you can escape greater than and less than characters with a backslash `\<liracer\>` becomes "\<liracer\>" as opposed to "<liracer>"(`<liracer>`).

It should replace the nickname as displayed to the left of all chat messages. `anon` is considered the default nickname and it should be possible to change it to something else. There of course needs to be a limit to how long and which characters the nicknames can contain. Something like all alphanumeric characters and maximum 10 characters or something like that.

**Comment by hungthezorba** [comment]
> I'm guessing this is a markup mistake, but I think I understand what you are asking either way. Btw you can escape greater than and less than characters with a backslash `\<liracer\>` becomes "<liracer>" as opposed to ""(`<liracer>`).

Thanks, I did not know and even notice that before.

> It should replace the nickname as displayed to the left of all chat messages. `anon` is considered the default nickname and it should be possible to change it to something else. There of course needs to be a limit to how long and which characters the nicknames can contain. Something like all alphanumeric characters and maximum 10 characters or something like that.

So it means keep the playerID, which is socket.id, on the hovering area right ?

**Comment by olavfosse** [comment]
>Thanks, I did not know and even notice that before.

No problem. I had the same problem myself in a previous PR / Issue.

>So it means keep the playerID, which is socket.id, on the hovering area right ?

Yes, indeed.

**Comment by hungthezorba** [comment]
Okay I can try working on this. How can I assign myself in this issue ?

**Comment by olavfosse** [comment]
Assigned. I believe only I can assign issues at the moment.
