### ISSUE TITLE
Messages overflow by expanding the box

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#6]
Messages overflow by expanding the box, simply setting `overflow-y: scroll`, did not fix the problem so I don't know how to fix it right now.

**Comment by olavfosse** [comment]
Demonstration
![overflow](https://user-images.githubusercontent.com/24797093/95683498-f294f300-0beb-11eb-84b4-d84d78be61ed.gif)

**Comment by olavfosse** [comment]
The component
https://github.com/olav35/liracer-rewrite/blob/da0385bddf9a1b114be70bc257ce8c9232392b5c/front/src/components/Messages.js#L19-L25
https://github.com/olav35/liracer-rewrite/blob/da0385bddf9a1b114be70bc257ce8c9232392b5c/front/src/components/Messages.js#L29-L33
Its parent
https://github.com/olav35/liracer-rewrite/blob/da0385bddf9a1b114be70bc257ce8c9232392b5c/front/src/components/ChatAndJoinButton.js#L7-L11
https://github.com/olav35/liracer-rewrite/blob/da0385bddf9a1b114be70bc257ce8c9232392b5c/front/src/components/ChatAndJoinButton.js#L72-L83

**Comment by vatsalsharma376** [comment]
I would like to work on this.

**Comment by olavfosse** [comment]
Great, feel free to submit a PR or post your findings if you make any progress.

**Comment by olavfosse** [comment]
Fix with #20 / 3fc643c5c149ddc2274eddca6c841b377ab3cb4f. Closing.

@vatsalsharma376 No more work is needed on this issue. Thanks for the effort though!
