### ISSUE TITLE
Chat overflow

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#67]
Instead of overflowing by getting a scrollbar, the chat overflows by expanding its box and in turn the viewport. This only happens when both the chat window and code window are open. 
https://user-images.githubusercontent.com/24797093/117499303-5497ba00-af7b-11eb-8719-b8ac2c7897c0.mp4

**Comment by khatibomar** [comment]
I like to take this issue

**Comment by olavfosse** [comment]
Thanks, I assigned it to you.

**Comment by olavfosse** [comment]
thanks!
