### ISSUE TITLE
Automatic scroling

### ISSUE THREAD

**Issue by olavfosse** [olavfosse/liracer#69]
When the user is scrolled all the way down to the bottom in chat, incoming messages should make the user automatically scroll down such that the latest message is viewable in its entiriety. The user should also be able to scroll up to view previous messages without being disrupted by the autoscroll.

**Comment by khatibomar** [comment]
Id like to work on this.

**Comment by olavfosse** [comment]
Great, I assigned it to you.

**Comment by OmarElKhatibCS** [comment]
Well someone missed up , how I can reset project and delete all last commits ? Like resync it with master

**Comment by OmarElKhatibCS** [comment]
I just notice That when you zoom the page , the code does not behave as Intended.

**Comment by olavfosse** [comment]
Thanks
