### ISSUE TITLE
Caps lock gets counted as a normal button press.

### ISSUE THREAD

**Issue by delivey** [olavfosse/liracer#77]
How to replicate:
Press caps lock and the character will become red and move to the new one.

What it should do instead:
Absolutely nothing. It shouldn't be counted as a valid character and just change capitalization.

Thankfully, the fix is very simple. Just adding `CapsLock` to this array should fix this https://github.com/olavfosse/liracer/blob/master/play.liracer.org/public/script.js#L124

**Comment by olavfosse** [comment]
Hey, thanks for the report. What is your OS snd browser?

**Comment by delivey** [comment]
Win 10 and Chrome 94

**Comment by olavfosse** [comment]
Alright, its blacklisted now.
